server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fluxgate
    username: postgres
    password: postgres
  liquibase:
    change-log: classpath:db/changelog/changelog-master.yaml
    enabled: true

  jpa:
    hibernate:
      ddl-auto: validate # important: let Liquibase own schema
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # datasource:
  #   url: jdbc:h2:mem:fluxgate_test;DB_CLOSE_DELAY=-1
  #   driver-class-name: org.h2.Driver
  #   username: sa
  #   password:
  application:
    name: fluxgate

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
